name: Run Tests and Analyze Logs

on:
  push:
    branches:
      - main
      - test-branch  # Trigger on push events in test-branch

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (if needed)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

#      # Step 4: Clean /tests directory except MyLibrary.py
#      - name: Clean tests directory except MyLibrary.py
#        run: |
#          find tests/ -type f ! -name 'MyLibrary.py' -delete

      # Step 5: Run Robot tests and generate logs
      - name: Run Robot tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/tests
          robot --loglevel DEBUG --outputdir results tests/ || true

      # Step 6: Show the generated logs (output.xml)
      - name: Show Test Logs
        run: cat results/output.xml

      # Step 7: Run Log Analyzer to categorize errors
      - name: Analyze Logs
        run: |
          python analyze_logs.py results/output.xml > error_report.txt

      # Step 8: Show the error report
      - name: Show Error Report
        run: cat error_report.txt

      # Step 9: Add annotations for error report
      - name: Annotate Error Report
        run: |
          echo "::error file=error_report.txt::$(cat error_report.txt)"

      # Step 10: Upload the results as artifacts
      - name: Upload Robot Framework Logs
        uses: actions/upload-artifact@v3
        with:
          name: robot-logs
          path: results/
