name: Run Tests and Analyze Logs

on:
  push:
    branches:
      - main
      - test-branch  # Trigger on push events in test-branch

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Check out code
        uses: actions/checkout@v4  # Updated to v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (including requests and RequestsLibrary)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install requests
          pip install robotframework-requests

      #      # Step 4: Clean tests directory except MyLibrary.py
      #      - name: Clean tests directory except MyLibrary.py
      #        run: |
      #          find tests/ -type f ! -name 'MyLibrary.py' -delete

      # Step 5: Run Robot tests and generate logs
      - name: Run Robot tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/tests
          robot --loglevel DEBUG --outputdir results tests/ || true

      # Step 6: Show the generated logs (output.xml)
      - name: Show Test Logs
        run: cat results/output.xml

      # Step to analyze logs and generate reports
      - name: Analyze Logs
        run: |
          python analyze_logs.py results/output.xml

      # Step 8: Show the error report
      - name: Show Error Report
        run: cat error_report.txt

      # Step to annotate only failed tests
      - name: Annotate Failed Tests
        if: failure()  # Only runs this step if a test has failed
        run: |
          echo "::error file=failed_tests_report.txt::$(cat failed_tests_report.txt)"

      # Step 10: Upload the results as artifacts
      - name: Upload Robot Framework Logs
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: robot-logs
          path: results/
