name: Run Tests and Analyze Logs

on:
  push:
    branches:
      - main
      - test-branch  # Trigger auf Push-Events im test-branch

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Repository auschecken
      - name: Check out code
        uses: actions/checkout@v3

      # Schritt 2: Python installieren
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Schritt 3: Abhängigkeiten installieren (falls nötig)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Schritt 4: Tests ausführen und Logs generieren
      - name: Run Robot tests
        run: |
          robot --loglevel DEBUG --outputdir results tests/ || true

      # Schritt 5: Zeige die generierten Logs (test_logs.txt)
      - name: Show Test Logs
        run: cat results/output.xml

      # Schritt 6: Log Analyzer ausführen, um Fehlerkategorien zu bestimmen
      - name: Analyze Logs
        run: |
          python analyze_logs.py results/output.xml > error_report.txt

      # Schritt 7: Fehlerbericht anzeigen
      - name: Show Error Report
        run: cat error_report.txt

      # Schritt 8: Benachrichtigung durch Annotations hinzufügen
      - name: Annotate Error Report
        run: |
          echo "::error file=error_report.txt::$(cat error_report.txt)"

      # Schritt 9: Lade die Ergebnisse als Artefakte hoch
      - name: Upload Robot Framework Logs
        uses: actions/upload-artifact@v2
        with:
          name: robot-logs
          path: results/
