name: Run Robot Tests

on:
  push:
    branches:
      - test-branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Debugging step to confirm file location
      - name: List files in the current directory
        run: ls -R

      # Install Python and Robot Framework
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Robot Framework
        run: |
          pip install robotframework

      # Run the Robot Framework test cases
      - name: Run Robot tests
        run: |
          robot test.robot

      # Upload test results
      - name: Upload Robot logs
        uses: actions/upload-artifact@v3
        with:
          name: robot-results
          path: output/
